// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/item/item.proto

package go_micro_srv_item

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Item struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_item_5f0c59a4b2fb9745, []int{0}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Item) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type GetItemByNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemByNameRequest) Reset()         { *m = GetItemByNameRequest{} }
func (m *GetItemByNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetItemByNameRequest) ProtoMessage()    {}
func (*GetItemByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_item_5f0c59a4b2fb9745, []int{1}
}
func (m *GetItemByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemByNameRequest.Unmarshal(m, b)
}
func (m *GetItemByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemByNameRequest.Marshal(b, m, deterministic)
}
func (dst *GetItemByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemByNameRequest.Merge(dst, src)
}
func (m *GetItemByNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetItemByNameRequest.Size(m)
}
func (m *GetItemByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemByNameRequest proto.InternalMessageInfo

func (m *GetItemByNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_item_5f0c59a4b2fb9745, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Item                 *Item    `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	Items                []*Item  `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_item_5f0c59a4b2fb9745, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Response) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "go.micro.srv.item.Item")
	proto.RegisterType((*GetItemByNameRequest)(nil), "go.micro.srv.item.GetItemByNameRequest")
	proto.RegisterType((*Request)(nil), "go.micro.srv.item.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.item.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ItemService service

type ItemServiceClient interface {
	CreateItem(ctx context.Context, in *Item, opts ...client.CallOption) (*Response, error)
	GetItems(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	GetItemsByName(ctx context.Context, in *GetItemByNameRequest, opts ...client.CallOption) (*Response, error)
}

type itemServiceClient struct {
	c           client.Client
	serviceName string
}

func NewItemServiceClient(serviceName string, c client.Client) ItemServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.item"
	}
	return &itemServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *itemServiceClient) CreateItem(ctx context.Context, in *Item, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ItemService.CreateItem", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) GetItems(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ItemService.GetItems", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) GetItemsByName(ctx context.Context, in *GetItemByNameRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ItemService.GetItemsByName", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ItemService service

type ItemServiceHandler interface {
	CreateItem(context.Context, *Item, *Response) error
	GetItems(context.Context, *Request, *Response) error
	GetItemsByName(context.Context, *GetItemByNameRequest, *Response) error
}

func RegisterItemServiceHandler(s server.Server, hdlr ItemServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ItemService{hdlr}, opts...))
}

type ItemService struct {
	ItemServiceHandler
}

func (h *ItemService) CreateItem(ctx context.Context, in *Item, out *Response) error {
	return h.ItemServiceHandler.CreateItem(ctx, in, out)
}

func (h *ItemService) GetItems(ctx context.Context, in *Request, out *Response) error {
	return h.ItemServiceHandler.GetItems(ctx, in, out)
}

func (h *ItemService) GetItemsByName(ctx context.Context, in *GetItemByNameRequest, out *Response) error {
	return h.ItemServiceHandler.GetItemsByName(ctx, in, out)
}

func init() { proto.RegisterFile("proto/item/item.proto", fileDescriptor_item_5f0c59a4b2fb9745) }

var fileDescriptor_item_5f0c59a4b2fb9745 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x25, 0x4d, 0x4a, 0xd3, 0xab, 0x54, 0x89, 0x53, 0x11, 0x56, 0x58, 0xaa, 0x2c, 0x20, 0x10,
	0x46, 0x2a, 0xff, 0x80, 0x0f, 0x21, 0x16, 0x86, 0xb0, 0x30, 0xb0, 0x84, 0xf4, 0x54, 0x79, 0x70,
	0x5c, 0x6c, 0x53, 0xd4, 0x8d, 0x1f, 0xcd, 0x0f, 0x40, 0xbe, 0x34, 0x65, 0x20, 0xd0, 0x25, 0xc9,
	0xbb, 0xf7, 0xee, 0xdd, 0xdd, 0x53, 0xe0, 0x70, 0x69, 0x8d, 0x37, 0x97, 0xca, 0x93, 0xe6, 0x87,
	0x64, 0x8c, 0x07, 0x0b, 0x23, 0xb5, 0xaa, 0xac, 0x91, 0xce, 0xae, 0x64, 0x20, 0xf2, 0x17, 0x48,
	0x1e, 0x3c, 0x69, 0x1c, 0x43, 0x4f, 0xcd, 0x45, 0x34, 0x8d, 0x4e, 0x87, 0x45, 0x4f, 0xcd, 0x11,
	0x21, 0xa9, 0x4b, 0x4d, 0xa2, 0xc7, 0x15, 0xfe, 0xc6, 0x09, 0xf4, 0xcd, 0x47, 0x4d, 0x56, 0xc4,
	0x5c, 0x6c, 0x00, 0x66, 0x90, 0x56, 0xa5, 0xa7, 0x85, 0xb1, 0x6b, 0x91, 0x30, 0xb1, 0xc5, 0xf9,
	0x19, 0x4c, 0xee, 0xc9, 0x87, 0x01, 0xd7, 0xeb, 0xc7, 0x52, 0x53, 0x41, 0x6f, 0xef, 0xe4, 0xfc,
	0xd6, 0x3d, 0xfa, 0x71, 0xcf, 0x87, 0x30, 0xd8, 0xd0, 0xf9, 0x67, 0x04, 0x69, 0x41, 0x6e, 0x69,
	0x6a, 0x47, 0x28, 0x60, 0x50, 0x59, 0x2a, 0x3d, 0x35, 0xeb, 0xa5, 0x45, 0x0b, 0xf1, 0x1c, 0x92,
	0x70, 0x03, 0xef, 0x38, 0x9a, 0x1d, 0xc9, 0x5f, 0xd7, 0xc9, 0x30, 0xb9, 0x60, 0x11, 0x5e, 0x40,
	0x3f, 0xbc, 0x9d, 0x88, 0xa7, 0xf1, 0x7f, 0xea, 0x46, 0x35, 0xfb, 0x8a, 0x60, 0x14, 0xf0, 0x13,
	0xd9, 0x95, 0xaa, 0x08, 0x6f, 0x01, 0x6e, 0x78, 0x2c, 0xa7, 0xf5, 0x57, 0x77, 0x76, 0xdc, 0x41,
	0xb4, 0x97, 0xe4, 0x7b, 0x78, 0x07, 0xe9, 0x26, 0x0f, 0x87, 0x59, 0xa7, 0x94, 0x03, 0xd8, 0x65,
	0xf3, 0x0c, 0xe3, 0xd6, 0xa6, 0xc9, 0x15, 0x4f, 0x3a, 0x1a, 0xba, 0x92, 0xdf, 0xe1, 0xfc, 0xba,
	0xcf, 0x3f, 0xca, 0xd5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x80, 0x97, 0x2d, 0xb5, 0x41, 0x02,
	0x00, 0x00,
}
