version: '3.1'
services: 
  database:
    image: mongo
    ports:
      - 27017:27017

  user-service:
    build: ./user-service
    ports:
      - 50051:50051
    environment:
      MICRO_REGISTRY: "mdns"
      USER_SERVER_ADDR: ":50051"
      DB_HOST: "database:27017"

  email-service:
    build : ./email-service
    ports:
      - 50054:50054
    environment:
      MICRO_REGISTRY: "mdns"
      EMAIL_SERVER_ADDR: ":50054"
  
  item-service:
    build: ./item-service
    ports:
      - 50053:50051
    environment:
      ITEM_SERVER_ADDR: ":50051"
      MICRO_REGISTRY: "mdns"
